In [120]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold

## Features_dataset

In [585]:
df1 = pd.read_csv("dense_train.csv")

In [586]:
new_name = {'Unnamed: 0' : 'new_label'}

In [587]:
df1.rename(columns=new_name,inplace=True)

In [588]:
unique_values = df1['new_label'].unique()

In [589]:
unique_values

array(['NCGC00178831-03', 'NCGC00166114-03', 'NCGC00263563-01', ...,
       'NCGC00260828-01', 'NCGC00260687-01', 'NCGC00261465-01'],
      dtype=object)

In [590]:
df1.columns

Index(['new_label', 'AW', 'AWeight', 'Arto', 'BertzCT', 'Chi0', 'Chi1',
       'Chi10', 'Chi2', 'Chi3',
       ...
       'W3D', 'W3DH', 'WNSA1', 'WNSA2', 'WNSA3', 'WPSA1', 'WPSA2', 'WPSA3',
       'grav', 'rygr'],
      dtype='object', length=802)

In [591]:
#df1.drop(columns='new_label',inplace=True)
model_results = np.zeros((12,647))

## Label dataset

In [592]:
df2 = pd.read_csv("labels_train.csv")

In [593]:
new_name = {'Unnamed: 0' : 'new_label'}

In [594]:
df2.rename(columns=new_name,inplace=True)

In [595]:
df2

,new_label,NR.AhR,NR.AR,NR.AR.LBD,NR.Aromatase,NR.ER,NR.ER.LBD,NR.PPAR.gamma,SR.ARE,SR.ATAD5,SR.HSE,SR.MMP,SR.p53
0,NCGC00178831-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,NCGC00166114-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,NCGC00263563-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
3,NCGC00013058-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
4,NCGC00167516-01,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,NCGC00261292-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12056,NCGC00261245-01,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
12057,NCGC00260828-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12058,NCGC00260687-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12059,NCGC00261465-01,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Removing coorelated features

In [596]:
correlation_matrix = df1.corr()
correlation_threshold = 0.7  # Set your correlation threshold value
correlated_features = set()
for i in range(1,len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > correlation_threshold:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)
X = df1.drop(columns=correlated_features)

In [597]:
X

,new_label,AW,AWeight,Arto,Chi3ch,Chi4ch,Chi5ch,Chiv3c,Chiv4c,EstateVSA1,...,MoRSEV3,Petitj3D,RDFC10,RDFC13,RDFC22,RDFM3,RDFP5,RNCS,RPCS,grav
0,NCGC00178831-03,5.436720e+07,13.053,2.176,0.0,0.0,0.000,1.088,0.000,12.407,...,-0.325,0.805,-0.337,-0.054,0.037,1.092,4.809,0,83.808,88.147
1,NCGC00166114-03,1.268818e+07,22.123,2.065,0.0,0.0,0.000,1.655,0.000,105.090,...,2.296,0.943,-0.588,0.747,0.000,6.182,33.221,0,46.958,134.852
2,NCGC00263563-01,3.076932e+06,13.085,2.154,0.0,0.0,0.287,4.375,0.298,66.949,...,1.852,0.763,-1.225,0.703,-0.664,3.068,37.670,0,0.000,216.852
3,NCGC00013058-02,7.168569e+07,12.832,2.029,0.0,0.0,0.000,2.083,0.000,0.000,...,-3.228,0.732,-1.078,-0.060,0.296,2.047,33.235,0,700.786,238.265
4,NCGC00167516-01,7.989702e+06,12.936,2.124,0.0,0.0,0.572,2.944,0.000,100.318,...,-6.318,0.893,1.149,-1.688,-0.757,2.705,34.154,0,491.912,317.901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,NCGC00261292-01,1.428572e+07,14.255,2.000,0.0,0.0,0.096,0.321,0.000,12.407,...,-1.215,0.706,0.376,-0.174,0.000,0.326,5.429,0,254.365,29.148
12056,NCGC00261245-01,1.193182e+07,13.674,2.061,0.0,0.0,0.000,0.685,0.000,30.918,...,-2.362,0.827,0.550,-0.331,-0.021,0.961,18.126,0,268.098,93.636
12057,NCGC00260828-01,1.081800e+01,12.374,2.045,0.0,0.0,0.000,3.310,0.354,22.396,...,1.161,0.967,-0.589,0.081,0.087,0.907,24.295,0,605.744,91.670
12058,NCGC00260687-01,3.229000e+00,12.543,2.267,0.0,0.0,0.079,0.389,0.000,0.000,...,-0.989,0.925,-0.039,-0.020,0.000,0.539,3.226,0,80.674,28.201
12059,NCGC00261465-01,1.931035e+07,15.004,1.867,0.0,0.0,0.000,0.943,0.037,128.848,...,-0.700,0.948,-0.507,0.483,-0.263,1.135,30.145,0,355.061,87.731

In [411]:
def keep_selected_features(csv_path, selected_features):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(csv_path)
    # Keep only the selected features
    df_selected = df[selected_features]
    return df_selected

## Concaetenating labels and feature dataset

In [ ]:
merged_df = pd.merge(X, df2, on='new_label', how='inner')

In [556]:
merged_df

,AW,AWeight,Arto,Chi3ch,Chi4ch,Chi5ch,Chiv3c,Chiv4c,EstateVSA1,EstateVSA10,...,NR.AR.LBD,NR.Aromatase,NR.ER,NR.ER.LBD,NR.PPAR.gamma,SR.ARE,SR.ATAD5,SR.HSE,SR.MMP,SR.p53
0,5.436720e+07,13.053,2.176,0.0,0.0,0.000,1.088,0.000,12.407,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.268818e+07,22.123,2.065,0.0,0.0,0.000,1.655,0.000,105.090,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.076932e+06,13.085,2.154,0.0,0.0,0.287,4.375,0.298,66.949,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7.168569e+07,12.832,2.029,0.0,0.0,0.000,2.083,0.000,0.000,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,7.989702e+06,12.936,2.124,0.0,0.0,0.572,2.944,0.000,100.318,9.589,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,1.428572e+07,14.255,2.000,0.0,0.0,0.096,0.321,0.000,12.407,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12056,1.193182e+07,13.674,2.061,0.0,0.0,0.000,0.685,0.000,30.918,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12057,1.081800e+01,12.374,2.045,0.0,0.0,0.000,3.310,0.354,22.396,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12058,3.229000e+00,12.543,2.267,0.0,0.0,0.079,0.389,0.000,0.000,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12059,1.931035e+07,15.004,1.867,0.0,0.0,0.000,0.943,0.037,128.848,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [415]:
merged_df.fillna(0,inplace=True)

In [ ]:
merged_df = pd.merge(X, df2, on='new_label', how='inner')

## Predicting NR.AhR

In [417]:
columns_to_remove = ['NR.AR','NR.AR.LBD','NR.Aromatase','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_ahr = merged_df.drop(columns=columns_to_remove)

In [418]:
df_ahr

,AW,AWeight,Arto,Chi3ch,Chi4ch,Chi5ch,Chiv3c,Chiv4c,EstateVSA1,EstateVSA10,...,Petitj3D,RDFC10,RDFC13,RDFC22,RDFM3,RDFP5,RNCS,RPCS,grav,NR.AhR
0,5.436720e+07,13.053,2.176,0.0,0.0,0.000,1.088,0.000,12.407,0.000,...,0.805,-0.337,-0.054,0.037,1.092,4.809,0,83.808,88.147,0.0
1,1.268818e+07,22.123,2.065,0.0,0.0,0.000,1.655,0.000,105.090,0.000,...,0.943,-0.588,0.747,0.000,6.182,33.221,0,46.958,134.852,0.0
2,3.076932e+06,13.085,2.154,0.0,0.0,0.287,4.375,0.298,66.949,0.000,...,0.763,-1.225,0.703,-0.664,3.068,37.670,0,0.000,216.852,0.0
3,7.168569e+07,12.832,2.029,0.0,0.0,0.000,2.083,0.000,0.000,0.000,...,0.732,-1.078,-0.060,0.296,2.047,33.235,0,700.786,238.265,0.0
4,7.989702e+06,12.936,2.124,0.0,0.0,0.572,2.944,0.000,100.318,9.589,...,0.893,1.149,-1.688,-0.757,2.705,34.154,0,491.912,317.901,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,1.428572e+07,14.255,2.000,0.0,0.0,0.096,0.321,0.000,12.407,0.000,...,0.706,0.376,-0.174,0.000,0.326,5.429,0,254.365,29.148,0.0
12056,1.193182e+07,13.674,2.061,0.0,0.0,0.000,0.685,0.000,30.918,0.000,...,0.827,0.550,-0.331,-0.021,0.961,18.126,0,268.098,93.636,0.0
12057,1.081800e+01,12.374,2.045,0.0,0.0,0.000,3.310,0.354,22.396,0.000,...,0.967,-0.589,0.081,0.087,0.907,24.295,0,605.744,91.670,0.0
12058,3.229000e+00,12.543,2.267,0.0,0.0,0.079,0.389,0.000,0.000,0.000,...,0.925,-0.039,-0.020,0.000,0.539,3.226,0,80.674,28.201,0.0
12059,1.931035e+07,15.004,1.867,0.0,0.0,0.000,0.943,0.037,128.848,0.000,...,0.948,-0.507,0.483,-0.263,1.135,30.145,0,355.061,87.731,0.0

In [419]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif

In [420]:
X = df_ahr.drop(columns=['NR.AhR'])  # FeaturesX = df_ahr.drop(columns=['new_label','NR.AhR'])  # Features
y = df_ahr['NR.AhR']  # Target variable

In [421]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
12055    0.0
12056    0.0
12057    0.0
12058    0.0
12059    0.0
Name: NR.AhR, Length: 12060, dtype: float64

In [422]:
X

,AW,AWeight,Arto,Chi3ch,Chi4ch,Chi5ch,Chiv3c,Chiv4c,EstateVSA1,EstateVSA10,...,MoRSEV3,Petitj3D,RDFC10,RDFC13,RDFC22,RDFM3,RDFP5,RNCS,RPCS,grav
0,5.436720e+07,13.053,2.176,0.0,0.0,0.000,1.088,0.000,12.407,0.000,...,-0.325,0.805,-0.337,-0.054,0.037,1.092,4.809,0,83.808,88.147
1,1.268818e+07,22.123,2.065,0.0,0.0,0.000,1.655,0.000,105.090,0.000,...,2.296,0.943,-0.588,0.747,0.000,6.182,33.221,0,46.958,134.852
2,3.076932e+06,13.085,2.154,0.0,0.0,0.287,4.375,0.298,66.949,0.000,...,1.852,0.763,-1.225,0.703,-0.664,3.068,37.670,0,0.000,216.852
3,7.168569e+07,12.832,2.029,0.0,0.0,0.000,2.083,0.000,0.000,0.000,...,-3.228,0.732,-1.078,-0.060,0.296,2.047,33.235,0,700.786,238.265
4,7.989702e+06,12.936,2.124,0.0,0.0,0.572,2.944,0.000,100.318,9.589,...,-6.318,0.893,1.149,-1.688,-0.757,2.705,34.154,0,491.912,317.901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,1.428572e+07,14.255,2.000,0.0,0.0,0.096,0.321,0.000,12.407,0.000,...,-1.215,0.706,0.376,-0.174,0.000,0.326,5.429,0,254.365,29.148
12056,1.193182e+07,13.674,2.061,0.0,0.0,0.000,0.685,0.000,30.918,0.000,...,-2.362,0.827,0.550,-0.331,-0.021,0.961,18.126,0,268.098,93.636
12057,1.081800e+01,12.374,2.045,0.0,0.0,0.000,3.310,0.354,22.396,0.000,...,1.161,0.967,-0.589,0.081,0.087,0.907,24.295,0,605.744,91.670
12058,3.229000e+00,12.543,2.267,0.0,0.0,0.079,0.389,0.000,0.000,0.000,...,-0.989,0.925,-0.039,-0.020,0.000,0.539,3.226,0,80.674,28.201
12059,1.931035e+07,15.004,1.867,0.0,0.0,0.000,0.943,0.037,128.848,0.000,...,-0.700,0.948,-0.507,0.483,-0.263,1.135,30.145,0,355.061,87.731

In [423]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [424]:
Y_train

1374     0.0
3288     1.0
11969    0.0
11790    0.0
10095    0.0
        ...
11964    0.0
5191     0.0
5390     0.0
860      0.0
7270     1.0
Name: NR.AhR, Length: 9648, dtype: float64

In [425]:
from sklearn.ensemble import RandomForestClassifier

In [466]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_1 = RandomForestClassifier(n_estimators=150, random_state=42)

# Fit the classifier to your training data
rf_classifier_1.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=150, random_state=42)

In [467]:
predictions = rf_classifier_1.predict(X_test)

In [468]:
len(predictions)

2412

In [471]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 92.82752902155887

In [562]:
def prediction_model(test_set,model):
    predictions = model.predict(test_set)
    return predictions

## Predicting  NR.AR

In [473]:
columns_to_remove = ['NR.AhR','NR.AR.LBD','NR.Aromatase','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_ar = merged_df.drop(columns=columns_to_remove)

In [474]:
df_ar

,AW,AWeight,Arto,Chi3ch,Chi4ch,Chi5ch,Chiv3c,Chiv4c,EstateVSA1,EstateVSA10,...,Petitj3D,RDFC10,RDFC13,RDFC22,RDFM3,RDFP5,RNCS,RPCS,grav,NR.AR
0,5.436720e+07,13.053,2.176,0.0,0.0,0.000,1.088,0.000,12.407,0.000,...,0.805,-0.337,-0.054,0.037,1.092,4.809,0,83.808,88.147,0.0
1,1.268818e+07,22.123,2.065,0.0,0.0,0.000,1.655,0.000,105.090,0.000,...,0.943,-0.588,0.747,0.000,6.182,33.221,0,46.958,134.852,0.0
2,3.076932e+06,13.085,2.154,0.0,0.0,0.287,4.375,0.298,66.949,0.000,...,0.763,-1.225,0.703,-0.664,3.068,37.670,0,0.000,216.852,0.0
3,7.168569e+07,12.832,2.029,0.0,0.0,0.000,2.083,0.000,0.000,0.000,...,0.732,-1.078,-0.060,0.296,2.047,33.235,0,700.786,238.265,0.0
4,7.989702e+06,12.936,2.124,0.0,0.0,0.572,2.944,0.000,100.318,9.589,...,0.893,1.149,-1.688,-0.757,2.705,34.154,0,491.912,317.901,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,1.428572e+07,14.255,2.000,0.0,0.0,0.096,0.321,0.000,12.407,0.000,...,0.706,0.376,-0.174,0.000,0.326,5.429,0,254.365,29.148,0.0
12056,1.193182e+07,13.674,2.061,0.0,0.0,0.000,0.685,0.000,30.918,0.000,...,0.827,0.550,-0.331,-0.021,0.961,18.126,0,268.098,93.636,0.0
12057,1.081800e+01,12.374,2.045,0.0,0.0,0.000,3.310,0.354,22.396,0.000,...,0.967,-0.589,0.081,0.087,0.907,24.295,0,605.744,91.670,0.0
12058,3.229000e+00,12.543,2.267,0.0,0.0,0.079,0.389,0.000,0.000,0.000,...,0.925,-0.039,-0.020,0.000,0.539,3.226,0,80.674,28.201,0.0
12059,1.931035e+07,15.004,1.867,0.0,0.0,0.000,0.943,0.037,128.848,0.000,...,0.948,-0.507,0.483,-0.263,1.135,30.145,0,355.061,87.731,0.0

In [475]:
X = df_ar.drop(columns=['NR.AR'])
y = df_ar['NR.AR']  # Target variable

In [476]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
12055    0.0
12056    0.0
12057    0.0
12058    0.0
12059    0.0
Name: NR.AR, Length: 12060, dtype: float64

In [477]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [478]:
from sklearn.ensemble import RandomForestClassifier

In [479]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_2 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_2.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [480]:
predictions = rf_classifier_2.predict(X_test)

In [482]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.51741293532339

## Predicting NR.AR.LBD

In [483]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_ar_lbd = merged_df.drop(columns=columns_to_remove)

In [484]:
X = df_ar_lbd.drop(columns=['NR.AR.LBD'])
y = df_ar_lbd['NR.AR.LBD']  # Target variable

In [485]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [486]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_3 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_3.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [487]:
predictions = rf_classifier_3.predict(X_test)

In [488]:
predictions

In [489]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.60033167495854

## Predicting NR.Aromatase

In [490]:
columns_to_remove = ['NR.AhR','NR.AR','NR.AR.LBD','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_aromatase = merged_df.drop(columns=columns_to_remove)

In [491]:
X = df_aromatase.drop(columns=['NR.Aromatase'])
y = df_aromatase['NR.Aromatase']  # Target variable

In [492]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [493]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_4 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_4.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [494]:
predictions = rf_classifier_4.predict(X_test)

In [495]:
predictions

In [496]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.4759535655058

## Predicting NR.ER

In [497]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.AR.LBD','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_er= merged_df.drop(columns=columns_to_remove)

In [498]:
X = df_er.drop(columns=['NR.ER'])
y = df_er['NR.ER']  # Target variable

In [499]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [500]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_5 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_5.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [501]:
predictions = rf_classifier_5.predict(X_test)

In [502]:
predictions

In [503]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 92.74461028192371

## Predicting NR.ER.LBD

In [504]:
columns_to_remove = ['NR.AhR','NR.AR','NR.AR.LBD','NR.Aromatase','NR.ER','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_er_lbd = merged_df.drop(columns=columns_to_remove)

In [505]:
X = df_er_lbd.drop(columns=['NR.ER.LBD'])
y = df_er_lbd['NR.ER.LBD']  # Target variable

In [506]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [507]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_6 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_6.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [508]:
predictions = rf_classifier_6.predict(X_test)

In [509]:
predictions

In [510]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.35157545605307

## Predicting NR.PPAR.gamma

In [511]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [512]:
X = df_nr_ppar.drop(columns=['NR.PPAR.gamma'])
y = df_nr_ppar['NR.PPAR.gamma']  # Target variable

In [513]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [514]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_7 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_7.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [515]:
predictions = rf_classifier_7.predict(X_test)

In [516]:
predictions

In [517]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 97.92703150912106

## Predicting SR.ARE

In [518]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','NR.PPAR.gamma','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [519]:
X = df_nr_ppar.drop(columns=['SR.ARE'])
y = df_nr_ppar['SR.ARE']  # Target variable

In [520]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [521]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_8 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_8.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [522]:
predictions = rf_classifier_8.predict(X_test)

In [523]:
predictions

In [524]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 89.92537313432835

## Predicting SR.ATAD5

In [525]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','NR.PPAR.gamma','SR.HSE','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [526]:
X = df_nr_ppar.drop(columns=['SR.ATAD5'])
y = df_nr_ppar['SR.ATAD5']  # Target variable

In [527]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [528]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_9 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_9.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [529]:
predictions = rf_classifier_9.predict(X_test)

In [530]:
predictions

In [531]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.84908789386401

## Predicting SR.HSE

In [532]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','NR.PPAR.gamma','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [533]:
X = df_nr_ppar.drop(columns=['SR.HSE'])
y = df_nr_ppar['SR.HSE']  # Target variable

In [534]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [535]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_10 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_10.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [536]:
predictions = rf_classifier_10.predict(X_test)

In [537]:
predictions

In [538]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 95.93698175787728

## Predicting SR.MMP

In [539]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','SR.HSE','NR.PPAR.gamma','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [540]:
X = df_nr_ppar.drop(columns=['SR.MMP'])
y = df_nr_ppar['SR.MMP']  # Target variable

In [541]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [542]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_11 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_11.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [543]:
predictions = rf_classifier_11.predict(X_test)

In [544]:
predictions

In [545]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 90.96185737976784

## Predicting SR.p53

In [546]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','NR.PPAR.gamma']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [547]:
X = df_nr_ppar.drop(columns=['SR.p53'])
y = df_nr_ppar['SR.p53']  # Target variable

In [548]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [549]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_12 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_12.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [550]:
predictions = rf_classifier_12.predict(X_test)

In [551]:
predictions

In [552]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 95.06633499170812

,AW,AWeight,Arto,Chi3ch,Chi4ch,Chi5ch,Chiv3c,Chiv4c,EstateVSA1,EstateVSA10,...,MoRSEV3,Petitj3D,RDFC10,RDFC13,RDFC22,RDFM3,RDFP5,RNCS,RPCS,grav
0,5.436720e+07,13.053,2.176,0.0,0.0,0.000,1.088,0.000,12.407,0.000,...,-0.325,0.805,-0.337,-0.054,0.037,1.092,4.809,0,83.808,88.147
1,1.268818e+07,22.123,2.065,0.0,0.0,0.000,1.655,0.000,105.090,0.000,...,2.296,0.943,-0.588,0.747,0.000,6.182,33.221,0,46.958,134.852
2,3.076932e+06,13.085,2.154,0.0,0.0,0.287,4.375,0.298,66.949,0.000,...,1.852,0.763,-1.225,0.703,-0.664,3.068,37.670,0,0.000,216.852
3,7.168569e+07,12.832,2.029,0.0,0.0,0.000,2.083,0.000,0.000,0.000,...,-3.228,0.732,-1.078,-0.060,0.296,2.047,33.235,0,700.786,238.265
4,7.989702e+06,12.936,2.124,0.0,0.0,0.572,2.944,0.000,100.318,9.589,...,-6.318,0.893,1.149,-1.688,-0.757,2.705,34.154,0,491.912,317.901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,1.428572e+07,14.255,2.000,0.0,0.0,0.096,0.321,0.000,12.407,0.000,...,-1.215,0.706,0.376,-0.174,0.000,0.326,5.429,0,254.365,29.148
12056,1.193182e+07,13.674,2.061,0.0,0.0,0.000,0.685,0.000,30.918,0.000,...,-2.362,0.827,0.550,-0.331,-0.021,0.961,18.126,0,268.098,93.636
12057,1.081800e+01,12.374,2.045,0.0,0.0,0.000,3.310,0.354,22.396,0.000,...,1.161,0.967,-0.589,0.081,0.087,0.907,24.295,0,605.744,91.670
12058,3.229000e+00,12.543,2.267,0.0,0.0,0.079,0.389,0.000,0.000,0.000,...,-0.989,0.925,-0.039,-0.020,0.000,0.539,3.226,0,80.674,28.201
12059,1.931035e+07,15.004,1.867,0.0,0.0,0.000,0.943,0.037,128.848,0.000,...,-0.700,0.948,-0.507,0.483,-0.263,1.135,30.145,0,355.061,87.731

In [600]:
selectede_features = X.columns
selected_features

Index(['AW', 'AWeight', 'Arto', 'Chi3ch', 'Chi4ch', 'Chi5ch', 'Chiv3c',
       'Chiv4c', 'EstateVSA1', 'EstateVSA10',
       ...
       'MoRSEV3', 'Petitj3D', 'RDFC10', 'RDFC13', 'RDFC22', 'RDFM3', 'RDFP5',
       'RNCS', 'RPCS', 'grav'],
      dtype='object', length=148)

In [560]:
test_df = keep_selected_features("dense_test.csv", selected_features)

In [570]:
prediction1 = prediction_model(test_df,rf_classifier_1)
model_results[0] = prediction1
prediction2 = prediction_model(test_df,rf_classifier_2)
model_results[1] = prediction2
prediction3 = prediction_model(test_df,rf_classifier_3)
model_results[2] = prediction3
prediction4 = prediction_model(test_df,rf_classifier_4)
model_results[3] = prediction4
prediction5 = prediction_model(test_df,rf_classifier_5)
model_results[4] = prediction5
prediction6 = prediction_model(test_df,rf_classifier_6)
model_results[5] = prediction6
prediction7 = prediction_model(test_df,rf_classifier_7)
model_results[6] = prediction7
prediction8 = prediction_model(test_df,rf_classifier_8)
model_results[7] = prediction8
prediction9 = prediction_model(test_df,rf_classifier_9)
model_results[8] = prediction9
prediction10 = prediction_model(test_df,rf_classifier_10)
model_results[9] = prediction10
prediction11 = prediction_model(test_df,rf_classifier_11)
model_results[10] = prediction11

In [575]:
model_results

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [577]:
columns_sum = np.sum(model_results, axis=0)

In [580]:
for i in range(len(columns_sum)):
    if(columns_sum[i]>=1):
        print("Efficiency: ", 1-(1/12)*columns_sum[i])
    else:
        print("Efficiency: 1")

Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.8333333333333334
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.75
Efficiency:  0.6666666666666667
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.8333333333333334
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.6666666666666667
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.75
Efficiency:  0.75
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.75
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1